-- DB: ammdb ; username: matt ; password: eggman;

CREATE TABLE utente (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(256),
    cognome VARCHAR(256),
    data_nascita VARCHAR,
    email VARCHAR(256) UNIQUE,
    passwd VARCHAR(256) NOT NULL,
    url_foto_profilo VARCHAR(1024),
    citazione VARCHAR(1024)
);

CREATE TABLE gruppo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(256),
    n_utenti INTEGER,
    url_immagine VARCHAR(1024)
);

CREATE TABLE gruppo_utente (
    gruppo_id INTEGER,
    	FOREIGN KEY (gruppo_id) REFERENCES gruppo(id),
    utente_id INTEGER,
        FOREIGN KEY (utente_id) REFERENCES utente(id),
    PRIMARY KEY (gruppo_id, utente_id)
);

CREATE TABLE post_type (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name VARCHAR(24)
);

CREATE TABLE post (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    autore INTEGER,
    	FOREIGN KEY (autore) REFERENCES utente(id),
    to_user INTEGER,
    	FOREIGN KEY (to_user) REFERENCES utente(id),
    to_group INTEGER,
    	FOREIGN KEY (to_group) REFERENCES gruppo(id),
    contenuto VARCHAR(1024),
    url_allegato VARCHAR(1024),
    nome_allegato VARCHAR(256),
    tipo INTEGER,
    	FOREIGN KEY (tipo) REFERENCES post_type(id),
    ora_pubblicazione TIME,
    data_pubblicazione DATE
);

-- post type: solo testo
INSERT INTO post_type (id, type_name)
VALUES (1, 'TEXT');

-- post type: testo e immagine
INSERT INTO post_type (id, type_name)
VALUES (2, 'TEXT_AND_IMAGE');

-- post type: testo e link
INSERT INTO post_type (id, type_name)
VALUES (3, 'TEXT_AND_LINK');


-- popolamento tabella utente
INSERT INTO utente (id, nome, cognome, data_nascita, email, passwd, url_foto_profilo, citazione)
VALUES (default,
        'Kaz',
        'Miller',
        '1996-06-03',
        'admin@nope.com',
        'theCacheIsALie',
        'img/default.png',
        'Big Boss is watching you (O.O)');
        
INSERT INTO utente (id, nome, cognome, data_nascita, email, passwd, url_foto_profilo, citazione)
VALUES (default,
		'Nurset',
		'Gorke',
		'1983-06-03',
		'saltbae@nope.com',
		'noMoreSalt',
		'img/profilo0.jpg',
                'NerdBook does it better!');
		
INSERT INTO utente (id, nome, cognome, data_nascita, email, passwd, url_foto_profilo, citazione)
VALUES (default,
		'Donald',
		'Trump',
		'1946-06-14',
		'donaldino@nope.com',
		'LovinMexico',
		'img/profilo1.jpg',
                'NerdBook does it better!');
		
INSERT INTO utente (id, nome, cognome, data_nascita, email, passwd, url_foto_profilo, citazione)
VALUES (default,
		'Hilary',
		'Clinton',
		'1947-09-26',
		'hilary@nope.com',
		'LovinNuke',
		'img/profilo2.jpg',
                'NerdBook does it better!');
		
INSERT INTO utente (id, nome, cognome, data_nascita, email, passwd, url_foto_profilo, citazione)
VALUES (default,
		'Matt',
		'Bellamy',
		'1978-06-09',
		'mattbellamy@nope.com',
		'Drones666',
		'img/people0.jpg',
                'NerdBook does it better!');
		
INSERT INTO utente (id, nome, cognome, data_nascita, email, passwd, url_foto_profilo, citazione)
VALUES (default,
		'Freddie',
		'Mercury',
		'1946-09-05',
		'freddie@nope.com',
		'BreakFree',
		'img/people1.jpg',
                'NerdBook does it better!');
		
INSERT INTO utente (id, nome, cognome, data_nascita, email, passwd, url_foto_profilo, citazione)
VALUES (default,
		'Gabe',
		'Newell',
		'1962-11-03',
		'gaben@nope.com',
		'theMagicNumb3r',
		'img/people2.jpg',
                'NerdBook does it better!');
		

-- popolamento tabella gruppo
INSERT INTO gruppo (id, nome, n_utenti, url_immagine)
VALUES (default,
		'The BE SHARPS',
		1,
		'img/group0.jpg');
		
INSERT INTO gruppo (id, nome, n_utenti, url_immagine)
VALUES (default,
		'Sgt. Pepper Lonely Hearts Club Band',
		2,
		'img/group1.jpg');

		
-- popolamento tabella post
INSERT INTO post (id, autore, to_user, to_group, contenuto, tipo, url_allegato, nome_allegato, ora_pubblicazione, data_pubblicazione)
VALUES (default,
		2,
		NULL,
		NULL,
		'Ci siamo stufati di questo meme. Basta. Non ne possiamo piu!',
		1,
		NULL,
		NULL,
		CURRENT_TIME,
		CURRENT_DATE);
		
INSERT INTO post (id, autore, to_user, to_group, contenuto, tipo, url_allegato, nome_allegato, ora_pubblicazione, data_pubblicazione)
VALUES (default,
		3,
		2,
		NULL,
		'Io suggerirei di cambiarla con una migliore.',
		2,
		'img/post0.jpg',
		'Me me me me me me me me',
		CURRENT_TIME,
		CURRENT_DATE);
		
INSERT INTO post (id, autore, to_user, to_group, contenuto, tipo, url_allegato, nome_allegato, ora_pubblicazione, data_pubblicazione)
VALUES (default,
		4,
		3,
		NULL,
		'Pff, dilettante.',
		3,
		'https://www.youtube.com/watch?v=WkNL_cfVyWU',
		'Guarda qui!',
		CURRENT_TIME,
		CURRENT_DATE);
		
INSERT INTO post (id, autore, to_user, to_group, contenuto, tipo, url_allegato, nome_allegato, ora_pubblicazione, data_pubblicazione)
VALUES (default,
		5,
		NULL,
		1,
		'DIG',
		3,
		'https://www.youtube.com/watch?v=b4ozdiGys5g',
		'DOWWWWWWWWWN',
		CURRENT_TIME,
		CURRENT_DATE);
        
        
        
INSERT INTO gruppo_utente (gruppo_id, utente_id)
VALUES (1, 4);

INSERT INTO gruppo_utente (gruppo_id, utente_id)
VALUES (2, 1);

INSERT INTO gruppo_utente (gruppo_id, utente_id)
VALUES (2, 4);    
        
